import type { Metadata } from "next";
import "@/styles/globals.css";
import { createSupabaseServer } from "@/services/supabase";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = createSupabaseServer();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return redirect("/login");
  }


  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
